config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  devise_for :users, path: "", controllers: {
                       omniauth_callbacks: "omniauth_callbacks",
                     }

  devise_scope :user do
    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
      get "/sign_in" => "users/sessions#new"
      get "/sign_up" => "users/registrations#new"
    end

    authenticated :user do
      root to: "home#index", as: :authenticated_root
      # User
      get "/sign_out" => "users/sessions#destroy", method: :delete
      get "/show_profile/:id" => "users/profiles#show", as: :show_profile
      get "/edit_profile" => "users/profiles#edit", as: :edit_profile
      patch "/update_profile", to: "users/profiles#update", as: :update_profile

      # Resources
      resources :posts
      resources :friend_requests
      resources :friendships

      # User's notification feed
      get "notifications/feed", to: "notifications#feed"

      # Search
      post "search", to: "search#index", as: "search"
      post "search/suggestions", to: "search#suggestions", as: "suggestions"

      # Friend Request Actions
      get "friend_requests/create/:id" => "friend_requests#create", as: "send_friend_request"
      post "friend_requests/update/:id" => "friend_requests#update", as: "accept_friend_request"
      delete "friend_requests/destroy/:id" => "friend_requests#destroy", as: "deny_friend_request"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  avatar                 :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :text
#  image                  :string
#  last_name              :text
#  provider               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  uid                    :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  post_id                :bigint
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_post_id               (post_id)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#
class User < ApplicationRecord
  searchkick word_start: %i[first_name last_name], callbacks: :async

  has_many :posts, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :notifications, foreign_key: :recipient_id, dependent: :destroy
  has_many :friends, through: :friendships, source: :friend

  # has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[discord github]

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_name=(name)
    name = name.split(" ")
    first_name = name[0]
    last_name = name[1]
  end

  def self.from_omniauth(auth)
    logger.debug auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      logger.debug user
      user.full_name = auth.info.name
      # user.nickname = auth.info.nickname
      # user.profile_url = auth.info.urls.GitHub
      user.email = auth.info.email if auth.info.email.present?
      user.image = auth.info.image
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

  def online?
    # updated_at > 2.minutes.ago
  end

  def friends_with?(other_user)
    friends.include?(other_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to edit_profile_path, notice: "Profile successfully updated!"
    else
      flash.now[:alert] = "Profile update failed. Please check the errors."
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :image)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/profiles/edit.html.haml
= render PanelComponent.new do
  %div.mx-auto.w-full.justify-center.container.space-y-10.divide-y{ class: "divide-gray-900" }
    .mx-auto.flex.w-full.max-w-7xl.items-start.gap-x-8.px-4.py-10.sm:px-6.lg:px-8
      = render ColumnComponent.new type: "aside" do
        %div.px-4.sm:px-0
          %h2.text-base.font-semibold.leading-7.text-gray-900 Profile
          %p.mt-1.text-sm.leading-6.text-gray-600 All of this public! You don't have to share your real name.
      = render ColumnComponent.new type: "main" do
        = simple_form_for @user, url: update_profile_path, method: :patch, html: { multipart: true } do |f|
          %div.px-4.py-6.sm:p-8.bg-white.shadow-sm.ring-1.ring-gray-900.sm:rounded-xl.md:col-span-2
            %div.grid.max-w-2xl.grid-cols-1.gap-x-6.gap-y-8.sm:grid-cols-6
              %div.sm:col-span-4
                = f.label :first_name, class: "block text-sm font-medium leading-6 text-gray-900"
                .mt-2
                  %div.flex.rounded-md.shadow-sm.ring-1.ring-inset.ring-gray-300.focus-within:ring-2.focus-within:ring-inset.focus-within:ring-indigo-600.sm:max-w-md
                    = f.text_field :first_name, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6", placeholder: "www.example.com"
              %div.sm:col-span-4
                = f.label :last_name, class: "block text-sm font-medium leading-6 text-gray-900"
                .mt-2
                  %div.flex.rounded-md.shadow-sm.ring-1.ring-inset.ring-gray-300.focus-within:ring-2.focus-within:ring-inset.focus-within:ring-indigo-600.sm:max-w-md
                    %span.flex.select-none.items-center.pl-3.text-gray-500.sm:text-sm #{@user.first_name}
                    = f.text_field :last_name, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6", placeholder: "www.example.com"
              %div.sm:col-span-4
                = f.label :image, class: "block text-sm font-medium leading-6 text-gray-900"
                .mt-2
                  %div.flex.rounded-md.shadow-sm.ring-1.ring-inset.ring-gray-300.focus-within:ring-2.focus-within:ring-inset.focus-within:ring-indigo-600.sm:max-w-md
                    %span.flex.select-none.items-center.pl-3.text-gray-500.sm:text-sm url:
                    = f.text_field :image, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6", placeholder: @user.image
                  %p.mt-2.text-sm.text-gray-500#image_link_description We are testing out URL profile pics.
              %div.col-span-full
                .mt-2.flex.items-center.gap-x-3
              %div.col-span-full.flex.justify-end.gap-x-6.border-t.px-4.py-4.sm:px-8{class: "border-gray-900/10"}
                = link_to "Cancel", "/", class: "btn btn-ghost text-sm font-semibold leading-6 text-gray-900"
                = f.button :submit, "Save", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              %div.col-span-full
                .mt-2.flex.justify-center.rounded-lg.border.border-dashed.border-gray-900.px-6.py-10
                  = render AvatarComponent.new src: current_user.image, alt: current_user.full_name
                  .flex.flex-col.justify-start.items-start.px-4
                    %div.text-center.text-xl.font-bold
                      = @user.full_name
                    %div.text-center.text-xl.font-bold.text-slate-400
                      User since #{time_ago_in_words(@user.created_at)} ago

app/views/users/profiles/show.html.haml
%div
  %div
    %img.h-32.w-full.object-cover.lg:h-48{alt: "", src: "https://images.unsplash.com/photo-1444628838545-ac4016a5418a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"}/
  .mx-auto.max-w-5xl.px-4.sm:px-6.lg:px-8
    .-mt-12.sm:-mt-16.sm:flex.sm:items-end.sm:space-x-5
      .avatar.h-32.w-32
        = render AvatarComponent.new size: "32", src: @user.image, alt: "Profile picture for #{@user.full_name}"
      .mt-6.sm:flex.sm:min-w-0.sm:flex-1.sm:items-center.sm:justify-end.sm:space-x-6.sm:pb-1
        .mt-6.min-w-0.flex-1.sm:hidden.md:block
          %h1.truncate.text-2xl.font-bold.text-gray-900 #{@user.full_name}
        - unless @user == current_user
          %turbo-frame#add_friend.mt-6.flex.flex-col.justify-stretch.space-y-3.sm:flex-row.sm:space-x-4.sm:space-y-0
            %label.sr-only{ for: "send friend request" } Accept Friend Request
            = link_to(send_friend_request_path(@user.id), method: :get, remote: true, class: 'inline-flex justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50', id: "send friend request", data: { turbo_method: :get}) do
              = heroicon "user-plus", options: { class: "h-5 w-5 fill-slate-400" }
              %span Add Friend
    .mt-6.hidden.min-w-0.flex-1.sm:block.md:hidden
      %h1.truncate.text-2xl.font-bold.text-gray-900 #{@user.full_name}